server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: exchangeCalculationService
          uri: lb://currency-calculation/
          predicates:
            - Path=/api/v1/calculate/**